<a href="https://colab.research.google.com/github/xyz111131/AI-Tools-for-Statistical-Research/blob/main/neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

# Construct a multilayer percepton

In [ ]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(

            # 1st hidden layer
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            # 2nd hidden layer
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            # output layer
            torch.nn.Linear(20, num_outputs),
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits

# Instantiate a new neural network

In [ ]:
model = NeuralNetwork(50, 3)
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


## check the number of trainable parameters

In [ ]:
num_params = sum(
    p.numel() for p in model.parameters() if p.requires_grad
)
print("Total number of trainable model parameters:", num_params)

Total number of trainable model parameters: 2213


## access weight and bias of each layer

In [ ]:
print(model.layers[0].weight) # reqiuires_grad = True by default
print(model.layers[0].bias)

Parameter containing:
tensor([[-0.1270, -0.1235, -0.0318,  ...,  0.0499, -0.0037, -0.0451],
        [ 0.0331, -0.0755,  0.0495,  ...,  0.1029,  0.0117, -0.0777],
        [ 0.1091, -0.0833,  0.0509,  ...,  0.1118,  0.0009,  0.0739],
        ...,
        [-0.0589, -0.0708,  0.1203,  ..., -0.0330,  0.0449,  0.0539],
        [ 0.1156,  0.0501, -0.1127,  ...,  0.1195,  0.0051, -0.0781],
        [ 0.0532,  0.0403,  0.0339,  ...,  0.0695,  0.1030, -0.1271]],
       requires_grad=True)


In [ ]:
torch.manual_seed(123) # set seed for reproducibility

# Model inference/Forward pass

In [ ]:
X = torch.rand((1, 50))
out = model(X) # forward pass
print(out) # grad_fn: the last-used function to compute a variable in the computational graph, Addmm: matrix multiplication (mm) followed by an addition

tensor([[-0.0274, -0.0904,  0.1941]], grad_fn=<AddmmBackward0>)


In [ ]:
with torch.no_grad():  # no need to keep track of gradients for model inference
    out = model(X)
print(out)

tensor([[-0.0274, -0.0904,  0.1941]])


In [ ]:
with torch.no_grad():  # output class probabilities
    out = torch.softmax(model(X), dim=1)
print(out)

tensor([[0.3138, 0.2946, 0.3916]])
