<a href="https://colab.research.google.com/github/xyz111131/AI-Tools-for-Statistical-Research/blob/main/neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

# Construct a multilayer percepton

In [ ]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(

            # 1st hidden layer
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            # 2nd hidden layer
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            # output layer
            torch.nn.Linear(20, num_outputs),
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits

# Instantiate a new neural network

In [ ]:
model = NeuralNetwork(50, 3)
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


## check the number of trainable parameters

In [ ]:
num_params = sum(
    p.numel() for p in model.parameters() if p.requires_grad
)
print("Total number of trainable model parameters:", num_params)

Total number of trainable model parameters: 2213


## access weight and bias of each layer

In [ ]:
print(model.layers[0].weight) # requires_grad = True by default
print(model.layers[0].bias)

Parameter containing:
tensor([[ 0.0384, -0.1237,  0.0123,  ..., -0.0401,  0.0719,  0.0813],
        [-0.0349,  0.0736,  0.0471,  ..., -0.0938, -0.0984,  0.1176],
        [-0.1261, -0.0696,  0.0346,  ...,  0.0306, -0.0715, -0.0079],
        ...,
        [ 0.0114, -0.0642,  0.0739,  ...,  0.0511,  0.1395,  0.0930],
        [-0.1076,  0.0234, -0.0200,  ..., -0.1143, -0.0370, -0.0196],
        [-0.0919,  0.0612, -0.0420,  ..., -0.1075,  0.0575,  0.0357]],
       requires_grad=True)
Parameter containing:
tensor([-0.0217,  0.0617,  0.1377, -0.0047, -0.0332,  0.0470,  0.0687, -0.1031,
         0.0265,  0.0346,  0.0989, -0.1352,  0.0295, -0.0514, -0.0288, -0.0126,
        -0.0749,  0.0281,  0.1013, -0.0180, -0.1070, -0.0485,  0.0279, -0.0404,
        -0.0530, -0.0726,  0.1120, -0.0487, -0.1165, -0.0191],
       requires_grad=True)


In [ ]:
torch.manual_seed(123) # set seed for reproducibility

# Model inference/Forward pass

In [ ]:
X = torch.rand((1, 50))
out = model(X) # forward pass
print(out) # grad_fn: the last-used function to compute a variable in the computational graph, Addmm: matrix multiplication (mm) followed by an addition

tensor([[-0.0027,  0.1474, -0.2455]], grad_fn=<AddmmBackward0>)


In [ ]:
with torch.no_grad():  # no need to keep track of gradients for model inference
    out = model(X)
print(out)

tensor([[-0.0027,  0.1474, -0.2455]])


In [ ]:
with torch.no_grad():  # output class probabilities
    out = torch.softmax(model(X), dim=1)
print(out)

tensor([[0.3138, 0.2946, 0.3916]])
