<a href="https://colab.research.google.com/github/xyz111131/AI-Tools-for-Statistical-Research/blob/main/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.cuda.is_available())

True


# Create Tensor

In [ ]:

# create a 0D tensor (scalar) from a Python integer
tensor0d = torch.tensor(1)

# create a 1D tensor (vector) from a Python list
tensor1d = torch.tensor([1, 2, 3])

# create a 2D tensor from a nested Python list
tensor2d = torch.tensor([[1, 2], [3, 4]])

# create a 3D tensor from a nested Python list
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [ ]:

display(tensor3d)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [ ]:
print(f"Tensor shape: {tensor3d.shape}")
print(f"Tensor dimensionality (number of dimensions): {tensor3d.ndim}")

Tensor shape: torch.Size([2, 2, 2])
Tensor dimensionality (number of dimensions): 3


In [ ]:
import numpy as np
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
torch.tensor([1.,2.], requires_grad=True, device='cuda')

tensor([1., 2.], device='cuda:0', requires_grad=True)


# Tensor Data types

In [ ]:
print(tensor1d.dtype) #PyTorch adopts the default 64-bit integer data type

torch.int64


In [ ]:
tensor1d = torch.tensor([1, 2, 3], dtype = torch.int32)
print(tensor1d.dtype)

torch.int32


In [ ]:
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)
display(floatvec)

torch.float32


tensor([1., 2., 3.])

# Tensor operations

In [ ]:
tensor2d = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])
tensor2d.reshape(3, 2)


tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
tensor2d.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
A = torch.rand(8, 3, 4)
B = torch.rand(8, 4, 5)
print(A @ B)
print(A[0,] @ B[0, ])

tensor([[[1.4408, 1.1296, 1.0626, 1.3916, 0.9751],
         [1.2663, 1.2513, 1.1418, 1.4020, 0.9859],
         [1.0937, 1.2364, 0.8991, 1.4025, 0.9544]],

        [[0.7199, 0.8126, 0.8144, 1.5860, 0.8850],
         [0.5227, 0.7433, 0.6785, 1.5895, 0.8834],
         [1.0651, 0.9552, 0.8930, 0.8486, 0.4297]],

        [[0.8031, 1.1214, 0.6833, 0.2742, 0.9787],
         [1.0080, 1.9839, 1.0994, 0.6923, 0.9109],
         [0.7495, 1.2431, 0.7186, 0.5189, 0.6958]],

        [[0.4629, 0.6140, 0.7691, 0.8891, 0.6131],
         [1.1267, 1.6021, 1.1211, 1.8695, 1.4931],
         [0.7212, 0.9568, 0.5037, 1.0127, 0.8388]],

        [[1.2814, 0.9575, 0.2280, 0.3398, 0.6507],
         [1.7188, 0.8919, 0.7668, 0.7327, 0.9757],
         [0.9074, 0.6577, 0.2401, 0.2849, 0.5130]],

        [[1.1439, 1.0682, 0.8301, 0.5280, 0.6219],
         [0.8150, 0.8473, 0.4119, 0.5419, 0.6054],
         [1.4945, 0.8399, 1.0750, 0.7846, 0.9011]],

        [[1.1667, 0.6527, 0.8047, 0.9778, 0.4285],
         [0.7743, 0

In [ ]:
print(torch.equal(A[0,] @ B[0, ], (A @ B)[0]))
print(torch.allclose(A[0,] @ B[0, ], (A @ B)[0]))

False
True


## view() never copies data, share memory

In [ ]:
x = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])
y = x.view(3, 2)
y[0,0] = 99
print(x[0])

tensor([99,  2,  3])


In [ ]:
x = torch.arange(12).view(3,4).t()
print(x.is_contiguous())
print(x[0])
y = x.view(4, 3)
y[0,0] = 99
print(x[0])

False
tensor([0, 4, 8])
tensor([99,  4,  8])


In [3]:
x = torch.rand(3,4)
y = x.T
print(x)
y[0]=0
print(x)
print(y)

tensor([[0.8128, 0.7736, 0.3855, 0.3029],
        [0.2327, 0.1219, 0.4067, 0.8640],
        [0.9512, 0.5073, 0.5774, 0.2576]])
tensor([[0.0000, 0.7736, 0.3855, 0.3029],
        [0.0000, 0.1219, 0.4067, 0.8640],
        [0.0000, 0.5073, 0.5774, 0.2576]])
tensor([[0.0000, 0.0000, 0.0000],
        [0.7736, 0.1219, 0.5073],
        [0.3855, 0.4067, 0.5774],
        [0.3029, 0.8640, 0.2576]])


## Creating a new tensor from a transpose using `.clone()`

When you use `x.T`, it returns a *view* of the original tensor `x` with its dimensions permuted. This means that both `x` and `x.T` share the same underlying memory. If you want to create a completely *independent* transposed tensor, you need to explicitly create a copy using the `.clone()` method.

In [5]:
x = torch.rand(3, 4)
print("Original tensor x:")
print(x)

y = x.T.clone() # Creates a new tensor y, which is a clone of the transpose of x
print("\nNew tensor y (cloned transpose of x):")
print(y)

# Modify y and observe that x is unaffected
y[0, 0] = 99.0
print("\nTensor y after modification (y[0,0] = 99.0):")
print(y)

print("\nTensor x after y was modified (x should be unchanged):")
print(x)

Original tensor x:
tensor([[0.7372, 0.3505, 0.5433, 0.0863],
        [0.0482, 0.9668, 0.6260, 0.2695],
        [0.4533, 0.9733, 0.9959, 0.5528]])

New tensor y (cloned transpose of x):
tensor([[0.7372, 0.0482, 0.4533],
        [0.3505, 0.9668, 0.9733],
        [0.5433, 0.6260, 0.9959],
        [0.0863, 0.2695, 0.5528]])

Tensor y after modification (y[0,0] = 99.0):
tensor([[9.9000e+01, 4.8222e-02, 4.5330e-01],
        [3.5046e-01, 9.6676e-01, 9.7330e-01],
        [5.4328e-01, 6.2599e-01, 9.9587e-01],
        [8.6304e-02, 2.6951e-01, 5.5276e-01]])

Tensor x after y was modified (x should be unchanged):
tensor([[0.7372, 0.3505, 0.5433, 0.0863],
        [0.0482, 0.9668, 0.6260, 0.2695],
        [0.4533, 0.9733, 0.9959, 0.5528]])
